reference-data:
  categories: Телефони, Планшети, Ноутбуки
  offices:
    - name: "Офіс 1"
      contactNumber: "+33333333333"
      address:
        city: "Kyiv"
        street: "Street 1"
    - name: "Офіс 2"
      contactNumber: "+44444444444"
      address:
        city: "Lviv"
        street: "Street 2"

#  reference-data.categories: Це список категорій товарів, які зберігаються у вигляді рядка.
#            Цей рядок розбивається на список у Java за допомогою анотації @Value.

#  reference-data.offices: Це список офісів, які зберігаються як об'єкти з полями name,
#            contactNumber, та address. address також є об'єктом, який містить поля city та street.
